### based on debug_stationMiss.ipynb

In [17]:
import pandas as pd
import numpy as np

expel_list=[1722,945,1732,1727,1733,1723,1724,1725,1726,1728,1729,1730,1731,944,946,947,948,950,951,952]

raw_data=pd.read_csv("../../Metro/station_transInfo.csv")
df = raw_data[~raw_data['stationID'].isin(expel_list)]

In [18]:
df

,Unnamed: 0,stationID,lon,lat,name,includeStation,neighborStation
0,0,2048,121.439716,31.171622,龙漕路,"[313, 1228]","[312, 314, 2012, 2038]"
1,1,2049,121.527849,31.224457,浦电路,"[418, 631]","[2010, 2015]"
2,2,2050,121.441840,31.225058,静安寺,"[243, 739]","[2041, 738, 2017, 2054]"
3,3,2051,121.422616,31.188487,宜山路,"[315, 402, 933]","[932, 2025, 2029, 314, 2044]"
4,4,2052,121.552971,31.205156,龙阳路,"[252, 752, 1621]","[751, 753, 1622, 251, 253]"
...,...,...,...,...,...,...,...
317,317,2043,121.412622,31.220079,中山公园,"[241, 318, 405]","[240, 2046, 2009, 2054]"
318,318,2044,121.416178,31.199283,虹桥路,"[316, 403, 1049]","[1048, 2051, 2037, 2046]"
319,319,509,121.415276,31.020130,东川路,NaN,"[508, 510]"
320,320,2046,121.412433,31.211456,延安西路,"[317, 404]","[2043, 2044]"
321,321,2047,121.485286,31.260925,海伦路,"[412, 1059]","[1058, 1060, 413, 2030]"

In [20]:
df.to_csv('../../Metro/station_transInfo_cleaned.csv',index=None)